# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t reverseproxy ./reverseproxy
- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-api-feed simfie/udagram-api-feed:v1
- docker tag udagram-api-user simfie/udagram-api-user:v1
- docker tag reverseproxy simfie/reverseproxy:v1
- docker tag udagram-frontend simfie/udagram-frontend:v1

  Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push simfie/udagram-api-feed:v1
- docker push simfie/udagram-api-user:v1
- docker push simfie/reverseproxy:v1
- docker push simfie/udagram-frontend:v1
